# generated by datamodel-codegen:
#   filename:  wgc_lemgo.geojson
#   timestamp: 2025-05-05T03:35:26+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CrsProperties(BaseModel):
    name: str


class Crs(BaseModel):
    properties: CrsProperties
    type: str


class Geometry(BaseModel):
    coordinates: List[float]
    type: str


class Properties(BaseModel):
    fid: int
    plz_code: str
    rides_plz: int
    subrides: float
    wgc_area_plz_rel: float
    wgc_area_plz_total: float
    


class Feature(BaseModel):
    geometry: Geometry
    properties: Properties
    type: str


class PtGeoJSON(BaseModel):
    crs: Crs
    features: List[Feature]
    name: str
    type: str
