# generated by datamodel-codegen:
#   filename:  lage_stopfinder_response.json
#   timestamp: 2025-05-02T12:21:47+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Parent(BaseModel):
    id: str
    name: str
    type: str


class Parent1(BaseModel):
    name: str
    type: str


class Properties(BaseModel):
    stopId: str


class AssignedStop(BaseModel):
    id: str
    isGlobalId: bool
    name: str
    disassembledName: Optional[str] = None
    type: str
    coord: List[float]
    parent: Parent1
    distance: Optional[int] = None
    duration: Optional[int] = None
    productClasses: Optional[List[int]] = None
    connectingMode: int
    properties: Properties


class Location(BaseModel):
    id: str
    name: str
    disassembledName: Optional[str] = None
    coord: List[float]
    buildingNumber: Optional[str] = None
    type: str
    parent: Parent
    assignedStops: List[AssignedStop]


class StopResponse(BaseModel):
    version: str
    locations: List[Location]
